### ISSUE TITLE
Form component missing hidden attribute

### ISSUE THREAD

**Issue by 1000Reasons** [blade-ui-kit/blade-ui-kit#164]
- Library Version: 0.4.0
- Laravel Version: 10
- PHP Version: 8.2

### Description:
When using Tailwind CSS "space-between" class i.e. space-y with the Form component, spacing is being applied to the hidden input fields for CSRF token and method. This can be fixed by adding a hidden attribute to the input fields.

### Steps To Reproduce:
1. Apply space-y to x-form component
2. Space is added in the wrong places

**Comment by 1000Reasons** [comment]
Just realised that the form component is using the laravel directives so this might need to be fixed in Laravel itself

**Comment by driesvints** [comment]
Oh that's indeed problematic. Is there any way we can negate the spacing on the hidden input using a class or something else? Other solution is to move the attributes onto a separate div surrounding the slot but unsure if that'll be breaking for some apps.

**Comment by 1000Reasons** [comment]
```css
.space-y-1 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0;
  margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse)));
  margin-bottom: calc(0.25rem * var(--tw-space-y-reverse));
}
```
This is the syntax for how the space-y works, adding a wrapping div might work, but like you mentioned it's a pretty big change in how the component works.
